import { AdminPageHeader } from "@/components/admin/page-header";
import { AdminTable } from "@/components/admin/data-table";
import { createClient } from "@/lib/supabase/server";
import { guardEditor } from "@/lib/auth";
import {
  deleteCertificate,
  setCertificateStatus,
} from "@/lib/actions/admin/certificates";

export const revalidate = 0;

const STATUS_BADGE: Record<string, "default" | "secondary" | "gold" | "outline" | "azure" | "destructive"> = {
  locked: "outline",
  eligible: "azure",
  issued: "gold",
  revoked: "destructive",
};

const STATUS_LABELS: Record<string, string> = {
  locked: "Locked",
  eligible: "Eligible",
  issued: "Issued",
  revoked: "Revoked",
};

export default async function AdminCertificatesPage() {
  await guardEditor();

  let rows: {
    id: string;
    student_name: string;
    course_title: string;
    certificate_no: string;
    verification_code: string;
    status: string;
    issue_date: string | null;
    created_at: string;
  }[] = [];

  try {
    const db = await createClient();
    const { data } = await db
      .from("certificates")
      .select("*")
      .order("created_at", { ascending: false });
    rows = ((data ?? []) as unknown as {
      id: string;
      student_name: string;
      course_title: string;
      certificate_no: string;
      verification_code: string;
      status: string;
      issue_date: string | null;
      created_at: string;
    }[]).map((c) => ({
      id: c.id,
      student_name: c.student_name,
      course_title: c.course_title,
      certificate_no: c.certificate_no,
      verification_code: c.verification_code,
      status: c.status,
      issue_date: c.issue_date,
      created_at: c.created_at,
    }));
  } catch {
    // Supabase not configured
  }

  return (
    <>
      <AdminPageHeader
        title="Certificates"
        description="Course completion certificates issued to students. Use the status dropdown to reissue or revoke."
      />

      <AdminTable
        rows={rows}
        columns={[
          { key: "student_name", header: "Student", type: "title", subKey: "course_title", sortable: true },
          { key: "certificate_no", header: "Certificate No." },
          { key: "verification_code", header: "Verify Code" },
          { key: "status", header: "Status", type: "badge", badgeMap: STATUS_BADGE, badgeLabels: STATUS_LABELS },
          { key: "issue_date", header: "Issue Date", type: "date", sortable: true },
          { key: "created_at", header: "Created", type: "date", sortable: true },
        ]}
        searchKeys={["student_name", "course_title", "certificate_no", "verification_code"]}
        searchPlaceholder="Search student, course or certificate ID…"
        emptyTitle="No certificates yet"
        emptyDescription="Certificates are generated by students when they complete a course."
        actions={{
          editBase: "/certificate/",
          viewBase: "/certificate/",
          slugKey: "id",
          statusKey: "status",
          statusOptions: ["issued", "revoked"],
          onStatusChange: setCertificateStatus as never,
          onDelete: deleteCertificate as never,
          label: "certificate",
        }}
      />
    </>
  );
}
